=== NIEM/Developer-Network-IEPD-Series--SuperHero/ism/base-xsd/external/IC/ISM/Test/Schema/unitTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:ism="urn:us:gov:ic:ism">

  <!-- ************************************************************* -->
  <!-- IMPORT IC INFORMATION SECURITY MARKING ATTRIBUTES ........... -->
  <!-- ************************************************************* -->
  <xsd:import namespace="urn:us:gov:ic:ism" schemaLocation="../../Schema/ISM/IC-ISM.xsd"/>
  
  
  
  <xsd:element name="ISMTestData">
    <xsd:complexType>
      <xsd:sequence minOccurs="1" maxOccurs="1">
        <xsd:element ref="ism:NoticeList" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="test" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
      <xsd:attributeGroup ref="ism:ISMRootNodeAttributeGroup"/>
      <xsd:attributeGroup ref="ism:ResourceNodeAttributeGroup"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="test">
    <xsd:complexType>
      <xsd:all minOccurs="1" maxOccurs="1">
        <xsd:element ref="name" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="sampleAttributes" minOccurs="1" maxOccurs="1"/>
        <xsd:element ref="ism:NoticeList" minOccurs="0" maxOccurs="1" />
        <xsd:element ref="banner" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="portion" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="authority" minOccurs="0" maxOccurs="1"/>
        <xsd:element ref="description" minOccurs="0" maxOccurs="1"/>        
      </xsd:all>
      <xsd:attributeGroup ref="ism:SecurityAttributesGroup"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="name" type="xsd:NCName"/>
  <xsd:element name="sampleAttributes">
    <xsd:complexType>
     <xsd:attributeGroup ref="ism:SecurityAttributesGroup"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="banner">
    <xsd:complexType mixed="true">
      <xsd:attribute name="expectFail" use="required" type="xsd:boolean"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="portion">
    <xsd:complexType mixed="true">
      <xsd:attribute name="expectFail" use="required" type="xsd:boolean"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:element name="authority" >
    <xsd:complexType mixed="true">
      <xsd:attribute name="expectFail" use="required" type="xsd:boolean"/>
    </xsd:complexType>
  </xsd:element>
  
  <xsd:element name="description" type="ism:ShortStringWithSecurityType"/>
  
  
</xsd:schema>

=== NIEM/Developer-Network-IEPD-Series--SuperHero/ism/base-xsd/external/IC/ISM/Test/testConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./testConfig.xsl"?>
<ISMTestData 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Schema/unitTest.xsd"
    xmlns:ism="urn:us:gov:ic:ism"
    ism:DESVersion="9"
    ism:ownerProducer="USA"
    ism:classification="U"
    ism:resourceElement="true"
    ism:createDate="2011-03-03">
    <ism:NoticeList ism:classification="U" ism:ownerProducer="USA">
        <ism:Notice>
            <ism:NoticeText ism:classification="U" ism:ownerProducer="USA">Sample Attributes do NOT represent actual classified data. IF the attributes themselves or the banner/portion marks are sensitive 
            that will be represented by the attributes on the test node.</ism:NoticeText>
        </ism:Notice>
        <ism:Notice ism:ownerProducer="USA" ism:classification="U" ism:noticeType="RD">
            <ism:NoticeText ism:classification="U" ism:ownerProducer="USA">Phoney RD notice</ism:NoticeText>
        </ism:Notice>
        
        <ism:Notice ism:ownerProducer="USA" ism:classification="U" ism:noticeType="FRD">
            <ism:NoticeText ism:classification="U" ism:ownerProducer="USA">Phoney FRD notice</ism:NoticeText>
        </ism:Notice>
    </ism:NoticeList>
    
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoCTS</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='NATO'/>
        <banner expectFail="false">//COSMIC TOP SECRET</banner>
        <portion expectFail="false">(//CTS) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoCTSA</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='NATO'
            ism:nonUSControls='ATOMAL'/>
        <banner expectFail="false">//COSMIC TOP SECRET//ATOMAL</banner>
        <portion expectFail="false">(//CTS//ATOMAL) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoCTSAOC</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='NATO'
            ism:disseminationControls="OC"
            ism:nonUSControls='ATOMAL'/>
        <banner expectFail="false">//COSMIC TOP SECRET//ATOMAL//ORCON</banner>
        <portion expectFail="false">(//CTS//ATOMAL//OC) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoCTSAB</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='NATO'
            ism:nonUSControls='ATOMAL BOHEMIA'/>
        <banner expectFail="false">//COSMIC TOP SECRET//ATOMAL/BOHEMIA</banner>
        <portion expectFail="false">(//CTS//ATOMAL/BOHEMIA) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoCTSB</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='NATO'
            ism:nonUSControls='BOHEMIA'/>
        <banner expectFail="false">//COSMIC TOP SECRET//BOHEMIA</banner>
        <portion expectFail="false">(//CTS//BOHEMIA) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoCTSBALK</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='NATO'
            ism:nonUSControls='BALK'/>
        <banner expectFail="false">//COSMIC TOP SECRET//BALK</banner>
        <portion expectFail="false">(//CTS//BALK) </portion>
    </test>
    
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoS</name>
        <sampleAttributes ism:classification='S'
            ism:ownerProducer='NATO'/>
        <banner expectFail="false">//NATO SECRET</banner>
        <portion expectFail="false">(//NS) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoSAT</name>
        <sampleAttributes ism:classification='S'
            ism:ownerProducer='NATO'
            ism:nonUSControls='ATOMAL'/>
        <banner expectFail="false">//NATO SECRET//ATOMAL</banner>
        <portion expectFail="false">(//NS//ATOMAL) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoC</name>
        <sampleAttributes ism:classification='C'
            ism:ownerProducer='NATO'/>
        <banner expectFail="false">//NATO CONFIDENTIAL</banner>
        <portion expectFail="false">(//NC) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoCA</name>
        <sampleAttributes ism:classification='C'
            ism:ownerProducer='NATO'
            ism:nonUSControls='ATOMAL'/>
        <banner expectFail="false">//NATO CONFIDENTIAL//ATOMAL</banner>
        <portion expectFail="false">(//NC//ATOMAL) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoR</name>
        <sampleAttributes ism:classification='R'
            ism:ownerProducer='NATO'/>
        <banner expectFail="false">//NATO RESTRICTED</banner>
        <portion expectFail="false">(//NR) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>NatoU</name>
        <sampleAttributes ism:classification='U'
            ism:ownerProducer='NATO'/>
        <banner expectFail="false">//NATO UNCLASSIFIED</banner>
        <portion expectFail="false">(//NU) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>HCS</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'
            ism:SCIcontrols="HCS"
            ism:disseminationControls="NF"/>
        <banner expectFail="false">TOP SECRET//HCS//NOFORN</banner>
        <portion expectFail="false">(TS//HCS//NF) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>SITK</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'
            ism:SCIcontrols="SI TK"/>
        <banner expectFail="false">TOP SECRET//SI/TK</banner>
        <portion expectFail="false">(TS//SI/TK) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>TS</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'/>
        <banner expectFail="false">TOP SECRET</banner>
        <portion expectFail="false">(TS) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>S</name>
        <sampleAttributes ism:classification='S'
            ism:ownerProducer='USA'/>
        <banner expectFail="false">SECRET</banner>
        <portion expectFail="false">(S) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>C</name>
        <sampleAttributes ism:classification='C'
            ism:ownerProducer='USA'/>
        <banner expectFail="false">CONFIDENTIAL</banner>
        <portion expectFail="false">(C) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>SI-G</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'
            ism:SCIcontrols="SI SI-G SI-G-ACDE TK"
            ism:disseminationControls="OC"/>
        <banner expectFail="false">TOP SECRET//SI-G ACDE/TK//ORCON</banner>
        <portion expectFail="false">(TS//SI-G ACDE/TK//OC) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>RSV-ABC-DEF</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'
            ism:SCIcontrols="RSV RSV-ABC RSV-DEF TK"
            />
        <banner expectFail="false">TOP SECRET//RSV-ABC-DEF/TK</banner>
        <portion expectFail="false">(TS//RSV-ABC-DEF/TK) </portion>
    </test>
    
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>SI-G-ABCD</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'
            ism:SCIcontrols="SI SI-G SI-G-ABCD"
            ism:disseminationControls="OC"/>
        <banner expectFail="false">TOP SECRET//SI-G ABCD//ORCON</banner>
        <portion expectFail="false">(TS//SI-G ABCD//OC) </portion>
    </test>
    
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>SI-G-ABCD</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'
            ism:SCIcontrols="SI SI-G SI-G-ABCD SI-G-ACDE"
            ism:disseminationControls="OC"/>
        <banner expectFail="false">TOP SECRET//SI-G ABCD ACDE//ORCON</banner>
        <portion expectFail="false">(TS//SI-G ABCD ACDE//OC) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>SI-G-ABCD-TK</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'
            ism:SCIcontrols="SI SI-G SI-G-ABCD SI-G-ACDE TK"
            ism:disseminationControls="OC"/>
        <banner expectFail="false">TOP SECRET//SI-G ABCD ACDE/TK//ORCON</banner>
        <portion expectFail="false">(TS//SI-G ABCD ACDE/TK//OC) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>FGI-AUS-SI</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='USA'
            ism:SCIcontrols="SI"
            ism:FGIsourceOpen="AUS"
            ism:disseminationControls="OC"/>
        <banner expectFail="false">TOP SECRET//SI//FGI AUS//ORCON</banner>
        <portion expectFail="false">(TS//SI//FGI AUS//OC) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
        <name>AUS-SI</name>
        <sampleAttributes ism:classification='TS'
            ism:ownerProducer='AUS'
            ism:SCIcontrols="SI"/>
        <banner expectFail="false">//AUS TOP SECRET//SI</banner>
        <portion expectFail="false">(//AUS TS//SI) </portion>
    </test>
    <test ism:ownerProducer="USA" ism:classification="U">
